### ISSUE TITLE
Force Power Items become invalid when an _ is in its id

### ISSUE THREAD

**Issue by StarLight-Oliver** [SpaxscE/lscs_public#13]
I haven't looked too closely at this, but I have found that when I put an _ in the id of powers the items end up being corrupted and not functioning as a force power item

**Comment by Blu-x92** [comment]
most likely the issue:

https://github.com/Blu-x92/lscs_public/blob/main/lua/lscs/init.lua#L80

dont have time to investigate it further rn

**Comment by MenschlichTv** [comment]
PR which fixes this issue: https://github.com/SpaxscE/lscs_public/pull/32
