### ISSUE TITLE
Prediction Error caused by not using util.SharedRandom

### ISSUE THREAD

**Issue by SpaxscE** [SpaxscE/lscs_public#45]
Bug introduced by pullrequest https://github.com/SpaxscE/lscs_public/pull/28

in
https://github.com/SpaxscE/lscs_public/blob/main/lua/weapons/weapon_lscs/sh_combo.lua#L229-L232

it plays different animation on client vs server. It should be using https://wiki.facepunch.com/gmod/util.SharedRandom

**Comment by SpaxscE** [comment]
needs testing. It might not even be fixable.

**Comment by BorpBorp** [comment]
I can probably push a new one using util.random. Cycling through the same animations in sequence is less appealing for users.
