### ISSUE TITLE
lscs_force_mana is updated 20+ times a second for all players.

### ISSUE THREAD

**Issue by NathanX-S** [SpaxscE/lscs_public#48]
Title.

**Comment by BorpBorp** [comment]
as luna might have suggested in the think hook:
!!!lscs_unforgiveable_playerGetAll_loop_in_think_hook.
(Might not even be related, its late and im trying my best lol)

From what I can see its just being called upon poorly. Allowing it to update repeatedly for maximum accuracy. Probably is worth looking more into, but I haven't noticed a major performance issues in cases with 40+ players.

**Comment by SpaxscE** [comment]
we could exclude players that have forceallowed set to false, but thats about it. It needs to update for all players, and it needs to update in that specific interval.

Is this an actual issue or are you just reporting this because the profiler is unhappy about it updating often?

**Comment by NathanX-S** [comment]
I'd say it's an actual issue. I think that it's generating needless net traffic. Could store the previous value in LUA and not update if it's not different?

**Comment by SpaxscE** [comment]
i dont think it re sends it when its unchanged, but i can throw in a check
