### ISSUE TITLE
Strange bug with deflecting shots

### ISSUE THREAD

**Issue by Kotyarishka** [SpaxscE/lscs_public#50]
I don't even know where to start. So, when you shoot someone, the animation gets “stuck”, but only under the roof (the weird part). The roof could be brush or prop, it doesn't matter. It also looks like a client error, as it doesn't synchronize and only depends on where the player was at the moment the lightsaber user was shot. I've attached a video with both POVs for better understanding

https://youtu.be/xTs99npe7vc

**Comment by BorpBorp** [comment]
Looks like the animation is failing to reset back to an original state after being played.
@SpaxscE

**Comment by SpaxscE** [comment]
i think this should fix it
